version: "3.8"

services:
  frontend:
    image: duylingo-admin-fe
    container_name: duylingo-admin-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8102:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
